# Generated by Django 5.0.6 on 2024-05-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_rename_profile_picture_userprofile_profile_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pictures',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture'),
        ),
    ]
